/**
 * Mutation types for the Search module
 */

const SET_HISTORY = 'SET_HISTORY';
const SET_LIMIT_HISTORY = 'SET_LIMIT_HISTORY';
const SET_CURRENT_HISTORY_ITEM = 'SET_CURRENT_HISTORY_ITEM';
const CLEAR_CURRENT_HISTORY_ITEM = 'CLEAR_CURRENT_HISTORY_ITEM';
const SET_CURRENT_HISTORY_ACTIVE_ID = 'SET_CURRENT_HISTORY_ACTIVE_ID';
const SET_CURRENT_TAB = 'SET_CURRENT_TAB';

export default {
  SET_HISTORY,
  SET_LIMIT_HISTORY,
  SET_CURRENT_HISTORY_ITEM,
  CLEAR_CURRENT_HISTORY_ITEM,
  SET_CURRENT_HISTORY_ACTIVE_ID,
  SET_CURRENT_TAB,
};
