/**
 * Mutation types for the Search module
 */

const SET_HISTORY_DATA = 'SET_HISTORY_DATA';
const SET_RESULTS_DATA = 'SET_RESULTS_DATA';
const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
const SET_HISTORY_ITEM = 'SET_HISTORY_ITEM';
const CLEAR_HISTORY_ITEM = 'CLEAR_HISTORY_ITEM';
const SET_CURRENT_MODAL_ITEM = 'SET_CURRENT_MODAL_ITEM';
const SET_TRANSITION_NAME = 'SET_TRANSITION_NAME';

export default {
  SET_HISTORY_DATA,
  SET_RESULTS_DATA,
  SET_CURRENT_ITEM,
  SET_HISTORY_ITEM,
  CLEAR_HISTORY_ITEM,
  SET_CURRENT_MODAL_ITEM,
  SET_TRANSITION_NAME,
};
